# based on https://docs.cloud.ploomber.io/en/latest/user-guide/github.html
name: Ingestion Pipeline

on:
  push:
    branches:
      # only deploy from the ploomber branch
      - dev

jobs:
  deploy-to-ploomber-cloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Fetch Initial Discord Messages
        env:
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install discord.py
          python backend/discord/get_messages.py
          

      - name: Run Haystack pipeline
        env:
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
        run: |
          tree .  
          python backend/haystack/fake_pipeline.py

      - name: Commit
        run: |
          git config user.name 'github-acions[bot]'
          git config user.email 'github-acions[bot]@users.noreply.github.com'

          git add .
          git commit -m 'github action : ingestion data'
          git push -f origin dev:ploomber_dev
