# based on https://docs.cloud.ploomber.io/en/latest/user-guide/github.html

name: Ploomber Cloud

on:
  push:
    branches:
      # only deploy from the ploomber branch
      - ploomber_dev

jobs:
  deploy-to-ploomber-cloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Fetch Initial Messages - Test
        env:
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          mkdir data
          pip install discord.py
          python backend/discord/get_messages.py

      - name: Test data
        env:
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
        run: |
          python backend/haystack/fake_pipeline.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ploomber-cloud hatch
          mkdir -p ploomber/wheels
          (hatch build && cp dist/*.whl ploomber/wheels)
          tree .

      - name: Deploy
        env:
          PLOOMBER_CLOUD_KEY: ${{ secrets.PLOOMBER_CLOUD_KEY_S }}
        run: |
          (cd ploomber && ploomber-cloud deploy)

          
      
